language: android
before_install:
- nvm install 6
- node --version
- mkdir "$ANDROID_HOME/licenses" || true
- openssl aes-256-cbc -K $encrypted_21ad6aa72baf_key -iv $encrypted_21ad6aa72baf_iv -in android/app/google-services.json.enc -out android/app/google-services.json -d
install:
- npm install
android:
  components:
  - tools
  - build-tools-26.0.1
  - build-tools-25.0.3
  - build-tools-23.0.1
  - build-tools-24.0.1
  - android-26
  - android-25
  - android-23
  - android-24
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
script:
- cd android && ./gradlew assembleRelease
