language: android
before_install:
- nvm install 6
- node --version
- mkdir "$ANDROID_HOME/licenses" || true

install:
- npm install
android:
  components:
  - tools
  - build-tools-26.0.1
  - android-26
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
script:
- npm run ci
- cd android && ./gradlew assembleRelease
